name: transit-map

volumes:
  traefik-certs:
  transit-map-db:


networks:
  transit-map:


services:
  # transit-map API server
  server:
    image: ghcr.io/j-markiewicz/transit-map:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - transit-map
    environment:
      - PORT=8000
      - DB=/db/transit-map.sqlite
    volumes:
      - transit-map-db:/db:rw
    labels:
      - traefik.enable=true
      # HTTPS
      - traefik.http.routers.backend.rule=Host(`transit-map.janm.dev`)
      - traefik.http.routers.backend.entrypoints=https
      - traefik.http.routers.backend.tls.certresolver=letsencrypt
      - traefik.http.routers.backend.tls.domains[0].main=transit-map.janm.dev
      - traefik.http.services.backend.loadbalancer.server.port=8000

  # Traefik reverse proxy
  traefik:
    image: traefik:2.11
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - DOMAIN="transit-map.janm.dev"
      - ACME_EMAIL="j.markiewicz@student.uj.edu.pl"
    volumes:
      - traefik-certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - transit-map
    command:
      # General setup
      - "--log.level=DEBUG"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
      # HTTP entrypoint (redirect to HTTPS)
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entryPoint.to=https"
      - "--entrypoints.http.http.redirections.entryPoint.scheme=https"
      # HTTPS / WSS entrypoint
      - "--entrypoints.https.address=:443"
      - "--entrypoints.https.http.tls.certResolver=letsencrypt"
      - "--entrypoints.https.http.tls.domains[0].main=transit-map.janm.dev"
      # Docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      # Let's Encrypt ACME Certs
      - "--certificatesResolvers.letsencrypt.acme.email=j.markiewicz@student.uj.edu.pl"
      - "--certificatesResolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesResolvers.letsencrypt.acme.storage=/certs/certs.json"
