name: Deploy website

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - run: |
          cd website
          yarn
          yarn build --base=/transit-map/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "website/dist/"
      - id: deployment
        uses: actions/deploy-pages@v4
